### ISSUE TITLE
Should generated-code files really be under version control?

### ISSUE THREAD

**Issue by leftaroundabout** [ajscholl/primitive-simd#2]
IMO this just bloats up the repository with redundant changes. I would
```bash
git rm -r src-128 src-256 src-512 src-no-vec
```
At most, I'd keep `src-256/Data/Primitive/SIMD/Class.hs` and for instance `src-256/Data/Primitive/SIMD/FloatX4.hs`, so each diff to `Generator.hs` would be accompanied by one easily-readable copy of the changes in the resultant code.

**Comment by ajscholl** [comment]
Maybe that would be good. I think it would be best if `Setup.hs` could be the generator, so generation of the source would be completly automated. Keeping an example sounds like a good idea, however it would be good to also see the handling of for example `Int`s as they are handled a little bit differently. Hopefully I will be able to work on this soon.

**Comment by ajscholl** [comment]
The `Setup.hs` script now takes care of code generation, so the redundant source is completely gone now. I decided not to keep examples of the generated code as then there would be the risk of them getting out of sync with the generator.
